# Generated by Django 5.2.1 on 2025-07-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='ifid',
        ),
    ]
