# Generated by Django 5.2.1 on 2025-07-15 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_rename_emp_id_employee_ifid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.CharField(default='jan 1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='intime1',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='intime2',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='outtime1',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='outtime2',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifid',
            field=models.IntegerField(unique=True),
        ),
    ]
