# Generated by Django 5.2.1 on 2025-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversion', '0004_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversioninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=250)),
                ('entities', models.CharField(max_length=250)),
            ],
            options={
                'unique_together': {('name', 'ifid', 'entities')},
            },
        ),
    ]
