# Generated by Django 5.2.1 on 2025-07-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0005_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversioninfo',
            unique_together=set(),
        ),
    ]
