# Generated by Django 5.2.1 on 2025-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversion', '0007_delete_conversioninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
