# Generated by Django 5.2.1 on 2025-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
