# Generated by Django 5.2.4 on 2025-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ifid', models.IntegerField(null=True)),
                ('mobileno', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('name', 'ifid')},
            },
        ),
        migrations.DeleteModel(
            name='movieinfo',
        ),
    ]
